-- Migration D: Content Hub workflow
--
-- New workflow:
--   1. generate-content-hub  → writes blog_article + youtube_script onto campaigns
--   2. generate-campaign-content → reads those two fields as the source of truth
--      and derives platform-specific posts from them instead of generating from scratch
--
-- Also:
--   • Adds ayrshare_profile_id + publish tracking to types (covered by earlier migrations,
--     this file just adds a comment-migration as a reminder to regenerate types via
--     `supabase gen types typescript --local > src/integrations/supabase/types.ts`)
--   • Marks social_auth_token as deprecated (column kept for backwards compat, never written)

-- Content hub columns on campaigns
ALTER TABLE public.campaigns
  ADD COLUMN IF NOT EXISTS blog_article      TEXT,
  ADD COLUMN IF NOT EXISTS youtube_script    TEXT,
  ADD COLUMN IF NOT EXISTS content_topic     TEXT,
  ADD COLUMN IF NOT EXISTS topic_source      TEXT CHECK (topic_source IN ('user_provided', 'ai_suggested'));

COMMENT ON COLUMN public.campaigns.blog_article IS
  'Long-form blog article generated by generate-content-hub. Used as source content for all platform posts.';
COMMENT ON COLUMN public.campaigns.youtube_script IS
  'Full YouTube video script derived from blog_article. Used for YouTube channel posts.';
COMMENT ON COLUMN public.campaigns.content_topic IS
  'The topic for this campaign''s content hub, either provided by the user or picked from AI suggestions.';
COMMENT ON COLUMN public.campaigns.topic_source IS
  'Whether the topic was user_provided or ai_suggested.';

-- Mark social_auth_token as deprecated — superseded by profiles.ayrshare_profile_id
COMMENT ON COLUMN public.profiles.social_auth_token IS
  'DEPRECATED: superseded by ayrshare_profile_id. Do not write. Will be removed in a future migration.';

-- Reminder: after running this migration regenerate TypeScript types:
--   supabase gen types typescript --local > src/integrations/supabase/types.ts
-- or use the Supabase dashboard type generator.
SELECT 1;
